services:
  golang:
    image: golang:1.22.7
    build: .
    container_name: golang_orders # Название контейнера
    # ports:
    #   - ":3000"  # Пробрасываем порт наружу
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
      - ../../proto:/proto
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: "make dev"
    restart: on-failure
    stop_grace_period: 3s
    networks:
      - gateway_database

networks:
  gateway_gatework:
    external: true
  gateway_database:
    external: true
      

