services:
  golang:
    image: golang:1.22.7
    build: .
    container_name: golang_orders # Название контейнера
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
    working_dir: /app
    command: "make dev"
    restart: on-failure
    stop_grace_period: 3s
    networks:
      - gatework
      - gateway_database

networks:
  gatework:
    external: true
  gateway_database:
    external: true
      

