services:
  golang:
    image: golang:1.23.6
    build: .
    container_name: golang_tools # Название контейнера
    ports:
      - "50041:50041"  # Пробрасываем порт наружу
    #   - ":3000"  # Пробрасываем порт наружу
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
      - ../../proto:/proto
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: "make dev"
    restart: on-failure
    stop_grace_period: 3s
    networks:
      - gateway_database

networks:
  gateway_gatework:
    external: true
  gateway_database:
    external: true
      

