services:
  golang:
    image: golang:1.22.7
    container_name: golang_gateway # Название контейнера
    ports:
      - "3000:3000"  # Пробрасываем порт наружу
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
    working_dir: /app
    command: "make dev"
    restart: on-failure
    networks:
      - gatework

networks:
  gatework:
    external: true
