services:
  golang:
    image: golang:1.22.7
    build: .
    # container_name: golang_gateway # Название контейнера
    ports:
      - "3000:3000"  # Пробрасываем порт наружу
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
      - ../../proto:/proto
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: "make dev"
    restart: on-failure
    stop_grace_period: 3s
    networks:
      - gatework
      - database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    # container_name: confectionary_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: confectionary
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    volumes:
      - ./storage/database/:/var/lib/mysql/
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin"]
      interval: 10s   # Интервал между проверками
      timeout: 5s     # Таймаут выполнения команды
      retries: 5      # Количество неудачных проверок перед пометкой как "unhealthy"
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - database


networks:
  gatework:
    driver: bridge
  database:
    driver: bridge

