services:
  golang:
    image: golang:1.22.7
    build: .
    container_name: golang_hello # Название контейнера
    ports:
      - "3101:3101"  # Пробрасываем порт наружу
    volumes:
      - .:/app  # Примонтируем текущую директорию внутрь контейнера
    # restart: on-failure
    working_dir: /app
    command: "make dev"
    networks:
      - gatework

networks:
  gatework:
    external: true
