# Создать и запустить контейнеры со сборкой 
# DEFAULT_CONFIG_PATH = ./configs/default_config.yaml
DEFAULT_CONFIG_PATH = ./configs/default_config.yaml

up:
	docker compose up 

dev:
	go run ./cmd/main/main.go \
		--config_path=$(DEFAULT_CONFIG_PATH)
