server:
  port: 3000

database:
  db_type: mysql
  host: localhost
  db_port: 3306
  db_name: airplanes
  admin_name: admin
  db_password: admin
  ssl: disable

jwt:
  secret_key: "super-duper-secret-key-4-jwt-auth"
  access_token_duration: "10m"
  refresh_token_duration: "8h"
