microservices:
  - components:
    url: http://golang_components:3000
    name: components

    base_path: /api

    routes:
      - ingredients-types:
        path: /ingredients/types
        methods:
          - GET
      - decorations-types:
        path: /decorations/types
        methods:
          - GET

      - ingredients-purchased:
        path: /ingredients/purchased
        methods:
          - GET
          - POST
          - PATCH
      - decorations-purchased:
        path: /decorations/purchased
        methods:
          - GET
          - POST
          - PATCH

      - ingredients-purchased-delete-empty:
        path: /ingredients/purchased/:purchased_component_id
        methods:
          - DELETE
      - decorations-purchased-delete-empty:
        path: /decorations/purchased/:purchased_component_id
        methods:
          - DELETE

      - products:
        path: /products
        methods:
          - GET
          - POST
          - PATCH

      - product-by-id:
        path: /products/:product_id
        methods:
          - GET

      - product-make:
        path: /products/:product_id/make
        methods:
          - POST

      - product-production-info:
        path: /products/:product_id/production-info
        methods:
          - GET

      - production-min-time:
        path: /products/:product_id/production-min-time
        methods:
          - GET

      - product-image:
        path: /products/:product_id/image
        methods:
          - PUT
          - GET

  - orders:
    url: http://golang_orders:3000
    name: orders

    base_path: /api

    routes:
      - orders:
        path: /orders
        methods:
          - GET
          - POST

      - order-update-status:
        path: /orders/:order_id/status
        methods:
          - PATCH

      - quality-controls:
        path: /quality-controls
        methods:
          - POST
          - PATCH

      - quality-controls-order-id:
        path: /quality-controls/order/:order_id
        methods:
          - GET
