microservices:
  - hello:
    url: http://golang_hello:3101
    name: hello

    routes:
      - hello:
        path: /hello
        methods:
          - GET

      - hello_id:
        path: /hello/:id
        methods:
          - GET
        middlewares:
          - auth
          - admin

      - goodbye:
        path: /goodbye
        methods:
          - GET
        middlewares:
          - auth

  - tools:
    url: http://golang_tools:3000
    name: tools

    routes:
