microservices:
  - components:
    url: http://golang_components:3000
    name: components

    base_path: /api

    routes:
      - ingredients-types:
        path: /ingredients/types
        methods:
          - GET
      - decorations-types:
        path: /decorations/types
        methods:
          - GET

      - ingredients-purchased:
        path: /ingredients/purchased
        methods:
          - GET
          - POST
          - PATCH
      - decorations-purchased:
        path: /decorations/purchased
        methods:
          - GET
          - POST
          - PATCH

      - ingredients-purchased-delete-empty:
        path: /ingredients/purchased/:purchased_component_id
        methods: DELETE
      - decorations-purchased-delete-empty:
        path: /decorations/purchased/:purchased_component_id
        methods: DELETE

      - products:
        path: /products
        methods:
          - GET
          - POST
          - PATCH

      - product-by-id:
        path: /products/:product_id
        methods:
          - GET

      - product-make:
        path: /products/:product_id/make
        methods:
          - POST

      - product-production-info:
        path: /products/:product_id/production-info
        methods:
          - GET

      - production-min-time:
        path: /products/:product_id/production-min-time
        methods:
          - GET

  - orders:
    url: http://golang_orders:3000
    name: orders

    base_path: /api

    routes:
      - orders:
        path: /orders
        methods:
          - GET
          - POST

  - tools:
    url: http://golang_tools:3000
    name: tools

    base_path: /api

    routes:
      - tool-types:
        path: /tool-types
        methods:
          - GET

      - tools:
        path: /tools
        methods:
          - GET
          - POST

      - tools-id:
        path: /tools/:id
        methods:
          - GET
          - PATCH
          - DELETE

      - tool-failures:
        path: /tool-failures
        methods:
          - GET
          - POST

      - tool-failures-add-fixed-at:
        path: /tool-failures/add-fixed-at
        methods:
          - POST

      - tool-failures-reasons:
        path: /tool-failures/reasons
        methods:
          - GET

  - hello:
    url: http://golang_hello:3101
    name: hello

    routes:
      - hello:
        path: /hello
        methods:
          - GET

      - hello_id:
        path: /hello/:id
        methods:
          - GET
        middlewares:
          - auth
          - admin

      - goodbye:
        path: /goodbye
        methods:
          - GET
        middlewares:
          - auth
