microservices:
  - confectionary:
    url: http://localhost:3001
    name: confectionary

    routes:
      - hello:
        path: /hello
        methods:
          - GET

      - goodbye:
        path: /goodbye
        methods:
          - GET
        middlewares:
          - auth
