microservices:
  - confectionary:
    url: http://golang_hello:3101
    name: confectionary

    routes:
      - hello:
        path: /hello
        methods:
          - GET

      - hello_id:
        path: /hello/:id
        methods:
          - GET
        middlewares:
          - auth
          - admin

      - goodbye:
        path: /goodbye
        methods:
          - GET
        middlewares:
          - auth
